module.exports={
    userRepository:require('./user-repository'),
    cityRepository:require('./city-repository'),
    crudRepository:require('./crud-repository'),
    flightRepository:require('./flight-repository'),
    bookingRepository:require('./booking-repository'),
    airplaneRepository:require('./airplane-repository'),
    airportRepository:require('./airport-repository')
}